apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 7000
      nodePort: 30390
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30394
---
apiVersion: v1
kind: Service
metadata:
  name: edge
spec:
  selector:
    app: edge
  type: NodePort
  ports:
    - protocol: TCP
      port: 5566
      targetPort: 5566
      nodePort: 30396